// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.startupExperimentPrefs.dom.push.alwaysConnect", true);
user_pref("app.normandy.user_id", "bff04ecf-5b79-4ddb-a48b-dc20371e4ab2");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1547717203);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 0);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 0);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 1034240);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1547717174);
user_pref("browser.laterrun.bookkeeping.sessionCount", 3);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 76);
user_pref("browser.newtabpage.activity-stream.impressionId", "{ef8383fe-1f9d-449f-92f9-38268c54b9ce}");
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1547647200);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 3);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1547719092228");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1547720863228");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1547717178043");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1547720778043");
user_pref("browser.search.region", "AU");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20181207224003");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1547717851");
user_pref("browser.slowStartup.averageTime", 1918);
user_pref("browser.slowStartup.samples", 3);
user_pref("browser.startup.homepage_override.buildID", "20181207224003");
user_pref("browser.startup.homepage_override.mstone", "64.0");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"toolbar-menubar\":[\"menubar-items\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\"],\"currentVersion\":15,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1547717177498");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "64.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "7ae65bba6a8049af9899904c3e755bcb");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 27);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppBuildId", "20181207224003");
user_pref("extensions.lastAppVersion", "64.0");
user_pref("extensions.lastPlatformVersion", "64.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"417c35c3-37f2-4f4a-b3cb-cc5ceccd3bdf\",\"screenshots@mozilla.org\":\"da9aa11b-6613-46fc-ba5e-eb25bf550a3c\",\"webcompat-reporter@mozilla.org\":\"fe65ec10-28e0-40c6-b76d-8d7c0b04174d\",\"webcompat@mozilla.org\":\"2649ccad-b1a5-4e28-80a9-93848490d7e7\"}");
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "e40edc29-69d1-4e59-be8d-4f8d38d88bc5");
user_pref("security.sandbox.plugin.tempDirSuffix", "7ec3d8e1-a639-4942-aa34-43238a3bf82c");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1547719089);
user_pref("toolkit.telemetry.cachedClientID", "f8676892-4a5a-43af-ad7f-315a3d9b7862");
user_pref("toolkit.telemetry.previousBuildID", "20181207224003");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
